version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nsa_php74
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - 80:80

  db:
    container_name: mysql8
    image: mysql:8.0
    volumes:
      - ../NSA-Services:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nsaservices_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: test123
    ports:
      - 6033:3306
